name: remind_dev
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.9
  cupertino_icons: ^1.0.6
  table_calendar: ^3.1.0
  shared_preferences: ^2.0.15
  shared_preferences_web: ^2.3.0
  flutter_colorpicker: ^1.0.3
  intl: 0.19.0
  provider: ^6.0.0
  http: ^1.2.2
  geolocator: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true